apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: '3.3.0'
  destination:
    name: in-cluster
    namespace: kyverno-system
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true