apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secrets-admin
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-controllers-secrets-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secrets-admin
subjects:
  - kind: ServiceAccount
    name: kyverno-admission-controller
    namespace: kyverno-system
  - kind: ServiceAccount
    name: kyverno-background-controller
    namespace: kyverno-system