apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: create-argocd-cluster-secret
spec:
  rules:
    - name: create-argocd-cluster-secret
      match:
        resources:
          kinds:
            - Secret
          namespaces:
            - '*'
          names:
            - vc-vcluster-platform
      generate:
        apiVersion: v1
        kind: Secret
        name: argocd-cluster-secret
        namespace: argocd
        data:
          name: "vcluster-platform"
          server: "https://kubernetes.default.svc"
          namespaces: ""  # Set if needed
          clusterResources: "true"  # Modify based on your need
          project: "default"
#          config: |
#            {
#              "tlsClientConfig": {
#                "caData": "{{ request.object.data.certificate-authority }}",
#                "certData": "{{ request.object.data.client-certificate }}",
#                "keyData": "{{ request.object.data.client-key }}",
#                "serverName": ""
#              },
#              "disableCompression": false
#            }
        synchronize: true