apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: vcluster-to-argocd-cluster
spec:
  rules:
    - name: vcluster-to-argocd-cluster
      match:
        resources:
          kinds:
            - Secret
          namespaceSelector:
            matchLabels:
              app.kubernetes.io/part-of: vcluster
          name: vc-vcluster-platform
      generate:
        apiVersion: v1
        kind: ConfigMap
        name: "{{ request.object.metadata.namespace }}-vcluster-platform"
        namespace: argocd
        synchronize: true
        data:
          metadata:
            annotations:
              generated-by: "kyverno"
            labels:
              argocd.argoproj.io/secret-type: cluster
          stringData:
            name: "{{ request.object.metadata.namespace }}"
            server: "vcluster-platform.vcluster-platform.svc.cluster.local"
            namespaces: "" # Optional, specify if needed
            clusterResources: "false" # Optional, set as needed
            project: "" # Optional, set as needed
            