apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: sample-app-0
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    path: deploy/manifests/sample-app-of-apps/sample-app-with-hook
    repoURL: https://github.com/alpadotsh/playground.git
    kustomize:
      namePrefix: sample-app-0-
      patches:
        - target:
            kind: Deployment
            name: nginx-deployment
          patch: |-
            - op: replace
              path: /spec/template/spec/containers[0].image
              value: nginx:1.27.2
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - PruneLast=true
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: sample-app-1
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    path: deploy/manifests/sample-app-of-apps/sample-app-with-hook
    repoURL: https://github.com/alpadotsh/playground.git
    kustomize:
      namePrefix: sample-app-1-
      patches:
        - target:
            kind: Deployment
            name: nginx-deployment
          patch: |-
            - op: replace
              path: /spec/template/spec/containers[0].image
              value: nginx:1.27.2
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - PruneLast=true
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: sample-app-2
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    path: deploy/manifests/sample-app-of-apps/sample-app-with-hook
    repoURL: https://github.com/alpadotsh/playground.git
    kustomize:
      namePrefix: sample-app-2-
      patches:
        - target:
            kind: Deployment
            name: nginx-deployment
          patch: |-
            - op: replace
              path: /spec/template/spec/containers[0].image
              value: nginx:1.27.2
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - PruneLast=true
      - CreateNamespace=true
