apiVersion: batch/v1
kind: Job
metadata:
  name: presync-job
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
        - name: example
          image: busybox
          command: ["sh", "-c", "sleep 5"]
      restartPolicy: Never