apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events-example
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alpadotsh/playground.git
    targetRevision: HEAD
    path: argo-events-example
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true