{
 "title": "Crossplane",
 "description": "v1",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "provider",
    "query": {
     "query": "label_values(controller_runtime_active_workers{namespace=\"crossplane-system\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pod Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container Memory in Crossplane Namespace by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"crossplane-system\", container=~\"$provider\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container CPU in Crossplane Namespace by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"crossplane-system\", container=~\"$provider\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Crossplane System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Reconciles by Controller (Top 10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(10, sum by (controller) (rate(controller_runtime_reconcile_total{container=~\"$provider\"}[5m])))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Workqueue Depth by Controller (Top 10)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 10 },
   "targets": [
    {
     "expr": "topk(10, sum by (name) (workqueue_depth{container=~\"$provider\"}))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Workqueue Duration",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(workqueue_queue_duration_seconds_bucket[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Resource Time To Reconcile Average by Kind",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(upjet_resource_ttr_sum{container=~\"$provider\"}[5m])/rate(upjet_resource_ttr_count{container=~\"$provider\"}[5m])",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Terraform CLI Time To Reconcile Average by Subcommand",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (subcommand) (rate(upjet_terraform_cli_duration_sum{container=~\"$provider\"}[5m])/rate(upjet_terraform_cli_duration_count{container=~\"$provider\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}