apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: crossplane
  namespace: crossplane-system
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: crossplane
  podMetricsEndpoints:
    - port: metrics
      interval: 30s